### ISSUE TITLE
Contribuição de design patterns (TS)

### ISSUE THREAD

**Issue by Daniel-Boll** [aserg-ufmg/engsoftmoderna#2]
Olá professor,

estou fazendo a matéria de PES-II na UNIOESTE campus Cascavel e estamos usando esse ótimo livro como guia. Alcançando o capítulo 6 agora estamos vendo os padrões de projetos e me deparei com esse repositório, gostaria de contribuir com ele _a priori_ com a linguagem TypeScript. 

Contudo ela apresenta algumas limitações e gostaria de saber o quão fiel deveria ser aos exemplos demonstrados em outras linguagens, fiz a primeira versão do `Factory.ts` gostaria de saber o que achas.

```ts
/**
 * Engenharia de Software Moderna - Padrões de Projeto (Cap. 6)
 * Prof. Marco Tulio Valente
 *
 * Exemplo do padrão de projeto Fábrica
 */

/**
 * Interface e classe dos objetos que serão fabricados.
 */
interface Channel {
  send(message: string): void;
}

class TCPChannel implements Channel {
  send(message: string): void {
    console.log(`TCP: ${message}`);
  }
}

class UDPChannel implements Channel {
  send(message: string): void {
    console.log(`UDP: ${message}`);
  }
}

/**
 * A classe ChannelFactory implementa um método fábrica estático.
 * Isto é, um método que centraliza a criação de objetos que
 * implementam a interface Channel
 *
 * Se amanhã quisermos que o sistema use UDPChannel, basta
 * mudar a implementação de create()
 */
abstract class ChannelFactory {
  abstract createChannel(): Channel;
}

/**
 * Para se poder se utilizar da classe abstrata do ChannelFactory com métodos
 * estáticos é necessário se utilizar este método de criação, através de uma classe
 * variável onde a tipagem define a herança por assim dizer.
 * */
const TCPChannelFactory: ChannelFactory = class {
  static createChannel(): Channel {
    return new TCPChannel();
  }
};

const UDPChannelFactory: ChannelFactory = class {
  static createChannel(): Channel {
    return new UDPChannel();
  }
};

function main() {
  function f() {
    const channel = TCPChannelFactory.createChannel();
    channel.send("Hello World!");
  }

  function g() {
    const channel = UDPChannelFactory.createChannel();
    channel.send("Hello World!");
  }

  f();
  g();
}

main();
```

É notável algumas diferenças, mas me deixe a par sobre o que acha da iniciativa e como, caso possível, poderia seguir com as contribuições para que no futuro ao completar todas eu faça um pull request.

Agradeço desde já,
Daniel Boll. :flower_playing_cards:

**Comment by mtov** [comment]
Olá Daniel, tudo bem?

Obrigado pela disponibilidade em implementar os exemplos de design patterns do nosso livro em TS.

Você poderia me mandar um e-mail, que aí podemos discutir melhor como fazer isso?

Meu mail é: mtvalente [at] gmail.com
